### ISSUE TITLE
use "CC0 1.0" license instead of "Apache License 2.0"

### ISSUE THREAD

**Issue by xuwei-k** [folio-sec/reladomo-first-example.g8#1]
https://github.com/folio-sec/reladomo-first-example.g8/blob/cbf6ca5931fc9986051088b945fee7755460a11e/LICENSE.txt

> We recommend licensing software templates under CC0 1.0, which waives all copyrights and related rights, similar to the “public domain.”

http://www.foundweekends.org/giter8/template.html

**Comment by seratch** [comment]
@itohiro73 What do you think about this? In my opinion, choosing Creative Commons looks reasonable.

>The tricky thing is that even permissive licenses such as MIT License and Apache License will require attribution to your template in the template user’s software. To remove all claims to the templated snippets, distribute it under CC0, which is an international equivalent to public domain.

**Comment by itohiro73** [comment]
This is an interesting point. Thanks @xuwei-k for raising this.

As we're following original Reladomo kata, it's not easy to convert this template to CC0 1.0 because we're re-distributing some source codes from reladomo-kata with Apache 2.0 license. 

I'd think we keep this template with Apache 2.0 as this template is rather meant for initial learning purpose than project creation.

I think we could create a different template from scratch with CC0 1.0, that could be used for general purpose such as project creation etc.
